var monthlyReport = new ReportBuilder()
                        .SetTitle("Monthly Sales")
                        .SetAuthor("Finance Team")
                        .SetPageSize("A4")
                        .SetOrientation("Landscape")
                        .SetWatermark("Confidential")
                        .SetHeader("Monthly Sales Report")
                        .SetFooter("Internal Use Only")
                        .SetIncludeCharts(false)
                        .Build();

var dailyReport = new ReportBuilder()
                        .SetTitle("Daily Sales")
                        .SetAuthor("IT Team")
                        .SetPageSize("A4")
                        .SetOrientation("Landscape")
                        .SetWatermark("Confidential")
                        .SetHeader("Daily Sales Report")
                        .SetFooter("Internal Use Only")
                        .SetIncludeCharts(true)
                        .SetIncludeTableOfContents(true)
                        .SetIncludePageNumbers(true)
                        .SetFontSize(14)
                        .SetFontFamily("Mono")
                        .Build();

var annualReport = new ReportBuilder()
                        .SetTitle("Annual Sales")
                        .SetAuthor("Accounting Team")
                        .Build();
